### ISSUE TITLE
[Bug] Connected WLAN's "Router" unknown in debug menu of HeliPort (but shown in SysPrefs)

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/HeliPort#104]
Although this could be is an **itlwm.kext** issue, I am reporting it here as it involves UI as well. Please assign this accordingly. Thanks.

**Describe the bug**
On **HeliPort.app** and with the debug menu shown (via Option key on keyboard and clicking on the menubar icon) I can see the connected WLAN network and IP address obtained and other kext information, but "Router" remains "Unknown".

**To Reproduce**
1. With Option key on keyboard, click on HeliPort icon on menubar;
2. Verify the SSID is connected and data is displayed;
3. Check "Router" information displayed;
4. On both 2.4GHz and 5GHz Wi-Fi networks of the same router, it's shown as "Unknown";
5. Go to System Preferences and Network section;
6. Click on the Intel WLAN device: Router information is there.

**Expected behavior**
Not sure what's supposed to be shown in "Router" so I can guess the Gateway information that's 192.168.1.1 i.e. my Asus router's IP. This information is displayed just fine in System Preferences -> Network -> ITLWM device tab.

**Screenshots**
Please see below both HeliPort and System Preferences:

![Router](https://user-images.githubusercontent.com/1313613/87853374-a4809400-c909-11ea-998c-9b6f199e4ccf.png)

![Network](https://user-images.githubusercontent.com/1313613/87853376-a6e2ee00-c909-11ea-99a3-95888e1c4285.png)

**Environment (please complete the following information):**
 - OS Version: Mojave 10.14.6
 - Software Version: Commits up to 2020-07-17

**Additional context**
I tested on both 2.4GHz and 5GHz of my Asus RT-AC58U router, same result. Thanks.

**Comment by williambj1** [comment]
CC @ErrorErrorError

**Comment by ErrorErrorError** [comment]
@mackonsti Do you have any logs that print out on Xcode? I wan't to know if it doesn't find the interface or ip address since it uses SystemConfiguration, which is the recommended API from Apple to find out network state.

**Comment by mackonsti** [comment]
I am sorry @ErrorErrorError I think I can't provide what you want. I do not run Xcode, I am on Mojave too. I ran the pre-compiled HeliPort.app from https://github.com/1hbb/OpenIntelWireless-Factory/releases
I am simply a power user not a developer :-( Let me know if I can do anything else to helping you?

As the driver does show the Router and DNS etc. in System Preferences via DHCP (not manually entered) is there no way to see how **itlwm** works maybe? (just an idea, possibly not even working the same way...)

**Comment by ErrorErrorError** [comment]
> I am sorry @ErrorErrorError I think I can't provide what you need. I do not run Xcode, I am on Mojave too. I ran the pre-compiled HeliPort.app from https://github.com/1hbb/OpenIntelWireless-Factory/releases
> I am simply a power user not a developer :-( Let me know if I can do anything else to helping you?
> 
> As the driver does show the Router and DNS etc. in System Preferences via DHCP (not manually entered) is there no way to see how **itlwm** works maybe? (just an idea, possibly not even working the same way...)

If you don't mind, can you open terminal and type `scutil` and press enter. After that, you should see a right arrow symbol,`>`. I want you to type `show State:/Network/Global/IPv4` and let me know if you see any information regarding router IP.

**Comment by mackonsti** [comment]
Of course. Here it is. I do get Router value. Had to disable `en0` first (the Ethernet controller) and repeated the command once WLAN `en1` had connected to my router:

```
$ scutil
> show State:/Network/Global/IPv4
<dictionary> {
  PrimaryInterface : en0
  PrimaryService : C6D7BE42-DB00-4CE9-8F17-1CC78F9EABA1
  Router : 192.168.1.1
}
> show State:/Network/Global/IPv4
<dictionary> {
  PrimaryInterface : en1
  PrimaryService : 84278F6F-6984-497E-B557-4714EFF85CE0
  Router : 192.168.1.1
}
> quit
```

**Comment by ErrorErrorError** [comment]
Hm, can you check if you see the router address showing in HeliPort? The commands seems to work fine so it should get those same results.

**Comment by mackonsti** [comment]
Yes now I can see it!
I think that after turning the Wireless controller OFF then ON, I can see it. Because straight from boot time, it doesn't seem to work (with HeliPort auto-started). Just a hunch. I can reboot soon, to check again. Could this be the case?

**Comment by ErrorErrorError** [comment]
> I think that after turning the Wireless controller OFF then ON, I can see it. Because straight from boot time, it doesn't seem to work (with HeliPort auto-started). Just a hunch. I can reboot soon, to check again. Could this be the case?

I am assuming it returns unknown because the primary interface was not `en1`, instead it was `en0`, as from the first time you ran `show State:/Network/Global/IPv4` it showed `en0` however HeliPort expected `en1`, which explains why it returned unknown.

**Comment by mackonsti** [comment]
OK so after rebooting and with en0 pre-disabled, I do get Router now displayed, with IPv6 disabled too:

![Router](https://user-images.githubusercontent.com/1313613/87858964-21bfff00-c932-11ea-824b-64c59b60d70a.png)

Please, a kind request:

a) Write on the main page that **users are advised to disable IPv6** via Terminal (as System Preferences drop-down list doesn't contain OFF anymore by default)

b) Change the text label "Address" to "MAC Address" on your menu list, just as it's shown in System Preferences -> Network -> Device properties. "Address" prompts to IP, without the word "MAC" (although a n00b may not distinguish IP and xx:xx:xx:xx LOL)

Not sure if this is solved now? Have you guys been able to run **just** IPv6 with the driver?

**Comment by ErrorErrorError** [comment]
> a) Write on the main page that **users are advised to disable IPv6** via Terminal (as System Preferences drop-down list doesn't contain OFF anymore by default)

Why should they disable IPv6?


> b) Change the text label "Address" to "MAC Address" on your menu list, just as it's shown in System Preferences -> Network -> Device properties. "Address" prompts to IP, without the word "MAC" (although a n00b may not distinguish IP and xx:xx:xx:xx LOL)

That is a question for @williambj1 since Apple does not do that on their Wi-Fi interface.

**Comment by mackonsti** [comment]
OK sure, sorry, I thought disabling IPv6 was the culprit here. Let me re-enable and reboot again a couple of times and report back.

As for the "Address" word, fine by me. Who are we to argue with Apple :-D

**Comment by ErrorErrorError** [comment]
> OK sure, sorry, I thought disabling IPv6 was the culprit here. Let me re-enable and reboot again a couple of times and report back. But as `en1` does get a Router, even with `en0` active, should we not get it displayed in HeliPort?

No worries I see why you say that lol. And technically yes you do get your router IP address, however `en0` is not from itlwm, as it shows the itlwm interface name on top of HeliPort, which it why it fails the condition and returns `Unknown` in HeliPort. Right now I am checking to see if I can just get the router ip for a specific interface regardless if it's primary or not.

**Comment by mackonsti** [comment]
> Right now I am checking to see if I can just get the router ip for a specific interface regardless if it's primary or not.

Not a bad idea! Hope you come up with something neat and clever!

So I rebooted with `en0` disabled and then rebooted as enabled, and despite some system _freezing_ and me being forced to turn off then on again the **itlwm** driver (when being the only network active device in Mojave) it seems that if `en0` is assigned to _active_ Ethernet and **itlwm** as `en1` then HeliPort does indeed get Router=Unknown. I have re-enabled IPv6 for all devices (LAN/WLAN) by the way...

However, I found a couple of other issues, not sure if you want me to create tickets, so I take the opportunity to ask you:

a) If you turn OFF Wi-Fi via HeliPort and back ON, there's no indicator (like that rotating icon, perhaps next to **Turn WiFi On** label) to indicate you that a scan is being done; the drop-down list is empty. It takes 5 seconds to show nearby SSIDs. Expected behaviour, but the macOS rotating icon would be welcome.

![Activity](https://user-images.githubusercontent.com/1313613/87860666-92214d00-c93f-11ea-87e6-0775c813df32.png)

b) If the **itlmw.kext** driver's `Info.plist` contains a valid SSID like the one I insert (due to custom editing it and entering my SSID/password) it seems that this may confuse HeliPort and won't load the last-saved SSID. For example, in `Info.plist` I set `WiFi_1` as my 2.4GHz SSID; but with HeliPort I choose each time (manually) the 5GHz SSID.

Should I delete all `<key>WiFiConfig</key>` dictionary entries in the kext i.e. `WiFi_1` to `WiFi_4` keys? Is this expected behaviour of HeliPort? If I don't auto-run-on-login HeliPort and I let the system boot OK, thus having initialised the kext, and then I manually run HeliPort, I **do get** the last-used SSID to be connected...

c) If I set **itlwm** to OFF via HeliPort, and I reboot, it seems that this "OFF" state is not respected without having HeliPort being executed/run; it seems HeliPort-dependent i.e. it doesn't set the device to "inactive" same as in System Preferences. This is expected behaviour?

Thank you! (sorry.... part of my job is IT specs validation at work :-D )

**Comment by ErrorErrorError** [comment]
> However, I found a couple of other issues, not sure if you want me to create tickets, so I take the opportunity to ask you:

If they are other issues that have not been created I would recommend creating an issue so it can be tracked easier. If it's a feature request, like scanning for networks, pls mark it as feature request or it's corresponding issue,bug, feature request etc...

> So I rebooted with en0 disabled and then rebooted as enabled, and despite some system freezing and me being forced to turn off then on again the itlwm driver (when being the only network active device in Mojave) it seems that if en0 is assigned to active Ethernet and itlwm as en1 then HeliPort does indeed get Router=Unknown. I have re-enabled IPv6 for all devices (LAN/WLAN) by the way...

Does `en0` have a Network connection and is it being used instead of the Wireless itlwm?

**Comment by mackonsti** [comment]
I will create the other tickets, thanks. Of course I will discriminate between request and bug.

> Does `en0` have a Network connection and is it being used instead of the Wireless itlwm?

Yes it's cable Ethernet plugged in and using **IntelMausi.kext** [by acidanthera](https://github.com/acidanthera/IntelMausi).

**Comment by williambj1** [comment]
That's actually quite odd since we BSD name directly from itlwm's API `&drv_info.bsd_name.0`

CC @zxystd

**Comment by ErrorErrorError** [comment]
> That's actually quite odd since we get BSD name directly from itlwm's API `&drv_info.bsd_name.0`

I mean I don't think it's an issue with itlwm, I just think that the priority of his system is not on the Wireless, but instead on the ethernet cable. You can have two, or more active network interfaces but only one of them is going to be used, and that is the one who is the one that should prioritize.

The only way I can get the router IP is from the network interface that has the priority since that is where the system is getting the connection from.

**Comment by mackonsti** [comment]
Yes @ErrorErrorError you are correct, my "service order" (to talk Apple) was Ethernet first:

![Service Order](https://user-images.githubusercontent.com/1313613/87872214-f7645500-c9b6-11ea-927a-91c071c22e90.png)

I wasn't aware that two or more active network devices (and with IP, I must stress) despite being both active, only the first would be used. I was under the impression there was some mild load balancing LOL. Merci

**Comment by Goshin** [comment]
@ErrorErrorError seems it only returns the primary network. A workaround I can think of is to parse the routing table.

An example: to get the gateway addr of `en1`
```bash
netstat -rn | egrep -o "default.*en1" | egrep -o "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"   # ipv4
```
