### ISSUE TITLE
[Feature Request] Show scan results immediately when Wi-Fi is turned back on

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/HeliPort#107]
**Is your feature request related to a problem? Please describe.**
If we turn OFF Wi-Fi via HeliPort and back ON, there's no indicator that a scan is being done; the drop-down list is empty. It takes 5 seconds or more to show nearby SSIDs. Could be expected behaviour, but the macOS rotating icon would be welcome so users aren't puzzled (or anxious)

**Describe the solution you'd like**
Add the macOS standard animation icon (rotating) that would indicate an SSID scan is taking place.
From a UI perspective, add this next to the text label **Turn WiFi Off** would make sense and would be more visible.
Turn animation off, when SSID scan is reported as complete.

![Activity](https://user-images.githubusercontent.com/1313613/87861427-69e91c80-c946-11ea-81bc-e70c1433676c.png)
(above sample is from another window, I just wanted to find out the reference animation, obviously _one_ rotating icon!)

**Describe alternatives you've considered**
While scanning SSIDs a grey menu item in the drop-down menu could also state "**Scanning Networks...**" instead. But that's also needed to be coded.
![Connected](https://user-images.githubusercontent.com/1313613/87861453-9dc44200-c946-11ea-86c5-fe91ea983028.png)
Add "Scanning Networks..." label as a disabled, greyed-out element UNDER "Turn WiFi Off" and ABOVE "Join Other Network..." with separator lines like "WiFi: Connected" on top. The space occupied by grey "Scanning Networks..." would then be replaced by the list of scanned SSIDs.

**Additional context**
Just helpful to those who click on the icon and may be wondering whatever happened to the SSIDs.

**Comment by williambj1** [comment]
Actually we already have "Wi-Fi: Looking for Networks" when itlwm is scanning.
In fact, I don't think we need to add any extra animations since Apple doesn't have them as well.

We might need to further optimize when should HeliPort get the scan results. Based on my understanding, itlwm should have a valid scan result when the adapter is turned back on and the Wi-Fi is connected, the results are not shown because HeliPort was delayed.

**Comment by mackonsti** [comment]
Thanks @williambj1 but the reason for posting this ticket is that there was no sign of such information or status display on HeliPort. Could it be that HeliPort wasn't connected to **itlmw**? I have not seen such **"Wi-Fi: Looking for Networks"** message on the drop-down menu.

**Comment by williambj1** [comment]
"Wi-Fi: Looking for Networks" only appears when itlwm hasn't connected to a network, background scanning was previously disabled so we didn't implement this when there is a connected network. This would be a Todo for our next version. (we're going to announce our first release within a few hours :) )

**Comment by mackonsti** [comment]
Thanks and congratulations for your announcement!
In any case, a visual status of a SSID scan being done, would be welcome. Right now, me personally I can't see anything if switching from OFF state to ON state the driver via HeliPort :-)
Thank you for your consideration and your great work.

**Comment by williambj1** [comment]
The network list appearance delay should be fixed in the latest master, now it appears instantly.
