### ISSUE TITLE
ERROR: No such module 'KeychainAccess' ?

### ISSUE THREAD

**Issue by XHL669** [OpenIntelWireless/HeliPort#108]
**Describe the bug**
After `sudo gem install cocoapods --pre`and`pod install` steps, there is still an error said "No such module 'KeychainAccess'"
I do not know what caused that. Prehaps my environment?

**To Reproduce**
1. Download the code and Install pods.
2. Then build the project
3. There is an error said "No such module 'KeychainAccess'"

**Expected behavior**
Build with no errors.

**Screenshots**
![截屏2020-07-19 上午11 44 16](https://user-images.githubusercontent.com/63577165/87866697-5cb84600-c9b7-11ea-89df-3a3aae52adf9.png)

**Environment (please complete the following information):**
 - OS Version: macOS 10.15.6

**Comment by ErrorErrorError** [comment]
Use the Heliport.xworkspace instead of the .xproject file

**Comment by XHL669** [comment]
> Use the `.xworkspace` instead of the `.xproject` file

Errr, successed. Thank you!
