### ISSUE TITLE
Auto connect to on login not working

### ISSUE THREAD

**Issue by naveenkrdy** [OpenIntelWireless/HeliPort#115]
Tried the latest [commit](https://github.com/OpenIntelWireless/HeliPort/commit/52c5b9a734781dea6e328306361f80f93a9be920) as of now and the auto connect on login stopped working again.
 it was working fine when i tried last time at this commit [`ab6c597`](https://github.com/OpenIntelWireless/HeliPort/commit/ab6c597d9abddd0c621934600c1f1e5a92cff463)

AX200
10.15.6 

Regards !

**Comment by ErrorErrorError** [comment]
> Tried the latest [commit](https://github.com/OpenIntelWireless/HeliPort/commit/52c5b9a734781dea6e328306361f80f93a9be920) as of now and the auto connect on login stopped working again.
> it was working fine when i tried last time at this commit [`ab6c597`](https://github.com/OpenIntelWireless/HeliPort/commit/ab6c597d9abddd0c621934600c1f1e5a92cff463)
> 
> AX200
> 10.15.6
> 
> Regards !

DId you disconnect from the network previously? If you disconnect from the network by clicking `Disconnect from SSID-NAME` then auto connect turns off for that specific network.

**Comment by naveenkrdy** [comment]
> DId you disconnect from the network previously? If you disconnect from the network by clicking `Disconnect from SSID-NAME` then auto connect turns off for that specific network.

No ! i did not.
no matter what i do it doesnt work with the latest commit.

**Comment by ErrorErrorError** [comment]
> > DId you disconnect from the network previously? If you disconnect from the network by clicking `Disconnect from SSID-NAME` then auto connect turns off for that specific network.
> 
> No ! i did not.
> no matter what i do it doesnt work with the latest commit.

I'm assuming tt has to do with the entity version not matching with the current version. Remove the saved ssid from Keychain Access and let me know if that works. I will see if there is a way to migrate previous entity to new ones in case if there any changes in the version.

**Comment by naveenkrdy** [comment]
> I'm assuming it has to do with the entity version not matching with the current version. Remove the saved SSID from Keychain Access and try to connect to the ssid using `Remember network option` and let me know if that works. I will see if there is a way to migrate previous entity to new ones in case if there any changes in the version.

yup ! that did the trick .
needed to delete the heliport entry from keychain access.
thanks !

**Comment by williambj1** [comment]
If you experience this issue after updating HeliPort to future versions, please reopen.
