### ISSUE TITLE
[Bug] Language Portuguese Brazilian PT-BR

### ISSUE THREAD

**Issue by jonasw8** [OpenIntelWireless/HeliPort#119]
HI! I am Brazilian and my language is Brazilian Portuguese. I would like to suggest the following HeliPort translation fixes

Line 16
"HeliPort running at an unexpected path" = "HeliPort running at an unexpected path"; // FIXME

Replace for 
"HeliPort running at an unexpected path" = "HeliPort está sendo executado em um caminho não esperado";

line 72
"itlwm Version Mismatch" = "Versão Imcompatível do itlwm";

Replace for
"itlwm Version Mismatch" = "Versão Incompatível do itlwm";

line 73
"itlwm is not running" = "itlwm is not running"; // FIXME

Replace for
"itlwm is not running" = "itlwm não está sendo executado";

**Comment by williambj1** [comment]
Could you please make a pull request including those changes? Thanks!

**Comment by jonasw8** [comment]
> 
> 
> Could you please make a pull request including those changes? Thanks!

How to pull resquest?

**Comment by jonasw8** [comment]
Pull request not work for me

![123](https://user-images.githubusercontent.com/53247355/88080953-2533d000-cb56-11ea-911b-d2b93721ce01.jpg)

**Comment by williambj1** [comment]
You should compare your fork and its origin's master, but not its origin's master with its origin's master.

Might sound a bit complicated so I would suggest you watch a guide on Youtube or read some GitHub Docs.

Thanks.

**Comment by igorkulman** [comment]
The easiest way to fix (any) localization is to find the file, so https://github.com/OpenIntelWireless/HeliPort/blob/master/HeliPort/Appearance/pt-BR.lproj/Localizable.strings in your case and click the "pencil" icon. 

<img width="252" alt="Screenshot 2020-07-22 at 11 05 18" src="https://user-images.githubusercontent.com/4746070/88157600-4276a600-cc0b-11ea-89a0-76331b68662c.png">

Github will take care of the rest, it will create a fork, let you edit the file, create a correct PR when you are done.

**Comment by marcelloinfoweb** [comment]
Fixed

**Comment by marcelloinfoweb** [comment]
> HI! I am Brazilian and my language is Brazilian Portuguese. I would like to suggest the following HeliPort translation fixes
> 
> Line 16
> "HeliPort running at an unexpected path" = "HeliPort running at an unexpected path"; // FIXME
> 
> Replace for
> "HeliPort running at an unexpected path" = "HeliPort está sendo executado em um caminho não esperado";
> 
> line 72
> "itlwm Version Mismatch" = "Versão Imcompatível do itlwm";
> 
> Replace for
> "itlwm Version Mismatch" = "Versão Incompatível do itlwm";
> 
> line 73
> "itlwm is not running" = "itlwm is not running"; // FIXME
> 
> Replace for
> "itlwm is not running" = "itlwm não está sendo executado";

Fixed
