### ISSUE TITLE
error: SwiftLint not installed, download from https://github.com/realm/SwiftLint

### ISSUE THREAD

**Issue by ProfDrLuigi** [OpenIntelWireless/HeliPort#121]
If I try to compile I get these error above.

**Comment by ErrorErrorError** [comment]
You need to install SwiftLint on your system before you can compile HeliPort. You can follow the link it shows you to install SwiftLint.

**Comment by ProfDrLuigi** [comment]
Yes I  know. I put it in "Podfile" and installed it. But ... error.

![grafik](https://user-images.githubusercontent.com/45099401/87975740-4ea81980-cacc-11ea-84f5-b497501ba101.png)
![grafik](https://user-images.githubusercontent.com/45099401/87975777-61225300-cacc-11ea-8e7e-071b6df5718f.png)

**Comment by ErrorErrorError** [comment]
Did you run `pod install` on terminal for that project?

**Comment by ProfDrLuigi** [comment]
Yes I did. have a look at my Screenshots above.

**Comment by ErrorErrorError** [comment]
> Yes I did. have a look at my Screenshots above. I compiled HeliPort every day again. But this time it stucks.

Yup sorry I didn't see that picture until after I sent the previous message. There hasn't been anything that changed in HeliPort project as far as I know. I used `brew install SwiftLint` methods so I can't really say as to why the pods aren't working, well in this case SwiftLint.

If you want you could try the `brew` method but HeliPort hasn't really changed anything regarding to scripts and SwiftLint.

**Comment by ProfDrLuigi** [comment]
brew install did the trick. But I don´t understand why it was working the days before and now (nothing is changed) it stucks. But ok ... Problem solved. :)

**Comment by Goshin** [comment]
SwiftLint should be installed as a global CLI tool via brew, otherwise, you need to add the executable path of the pod module into your `PATH` variable.

**Comment by ErrorErrorError** [comment]
> SwiftLint should be installed as a global CLI tool via brew, otherwise, you need to add the executable path of the pod module into your `PATH` variable.

It could also be included in Podfile via `pod 'SwiftLint'` since now the latest master has a script that checks if SwiftLint is installed via CocoaPods, however I am not sure which would be the most recommended way if having in the command line or just for the project itself via CocoaPods.

**Comment by Goshin** [comment]
> It could also be included in Podfile via pod 'SwiftLint' since now the latest master has a script that checks if SwiftLint is installed via CocoaPods,

sry but I don't see the check script?

**Comment by ErrorErrorError** [comment]
> sry but I don't see the check script?

```
if which "${PODS_ROOT}/SwiftLint/swiftlint" >/dev/null; then 
    ${PODS_ROOT}/SwiftLint/swiftlint
elif which swiftlint >/dev/null; then
    swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```
This script is in the latest commit https://github.com/OpenIntelWireless/HeliPort/commit/0222faeafe01d9af83baf1d54ac771c197859b9c.

You can find it here: 
![Screen Shot 2020-07-21 at 2 32 47 AM](https://user-images.githubusercontent.com/16653389/88025829-84fc8d80-cafa-11ea-8ccd-6865e97a12cd.png)

**Comment by Goshin** [comment]
oops I didn't notice the latest commit, so it should fix the issue.

**Comment by williambj1** [comment]
:)
