### ISSUE TITLE
[UI Improvement] Two quick improvements: Kext not running dialog / Reference to BSD in About

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/HeliPort#123]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
a) A little user-friendlier message that itlmw.kext is not running.
b) Improvement to BDS Clause 3 by including a URL reference.

**Describe alternatives you've considered**
Can't think of any alternatives except ignore them.

**Additional context**
a) Please expand the text when the driver is not running to something more friendlier, for example:
"The necessary WLAN driver is not found active on your system. Please verify that itlmw.kext is correctly installed and running."

b) Please fix, for the sake of being covered by BSD License, the About window RTF file with a URL reference, too (either a single mention or copy-paste the _actual_ license):

> **License**
> 
> This software is distributed through the 3-Clause BSD License, otherwise known as New BSD License. Read more at https://opensource.org/licenses/BSD-3-Clause

or the other, fuller approach:

> **License**
> 
> Copyright (c)2020. All rights reserved.
> 
> This software is distributed through the 3-Clause BSD License, otherwise known as New BSD License. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

![Kext Not Found](https://user-images.githubusercontent.com/1313613/88109190-605fee80-cbaa-11ea-9ce9-1eb3ede6ca2a.png)
![BDS-3-Clause](https://user-images.githubusercontent.com/1313613/88109222-6d7cdd80-cbaa-11ea-998b-a66b982b4f8c.png)
Thank you!

**Comment by Goshin** [comment]
Thanks for the advice.

**Comment by mackonsti** [comment]
Thanks guys, I keep coming second to similar demands, hopefully they will become unique some day LOL
