### ISSUE TITLE
[Bug] I can no longer compile Heliport

### ISSUE THREAD

**Issue by marcelloinfoweb** [OpenIntelWireless/HeliPort#127]
Command:

xcodebuild -workspace HeliPort.xcworkspace -scheme HeliPort -configuration Debug -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

![Captura de Tela 2020-07-22 às 08 48 31](https://user-images.githubusercontent.com/2093128/88172960-2cabb580-cbf8-11ea-98d8-d711f0d61cdc.png)

**Comment by Goshin** [comment]
Read the error carefully

```
pod install
```

**Comment by marcelloinfoweb** [comment]
> Read the error carefully
> 
> ```
> pod install
> ```

![Captura de Tela 2020-07-22 às 08 59 47](https://user-images.githubusercontent.com/2093128/88173896-bc9e2f00-cbf9-11ea-8af8-541688586525.png)

**Comment by williambj1** [comment]
Use Gitter for personal help requests. This is not a bug of our software, thanks.
