### ISSUE TITLE
I can't send a message at Gitter

### ISSUE THREAD

**Issue by marcelloinfoweb** [OpenIntelWireless/HeliPort#128]
Please don't delete, I need your help, I can't post here, and I can't post there, so where am I going?

![Captura de Tela 2020-07-22 às 08 46 44](https://user-images.githubusercontent.com/2093128/88177747-c034b480-cbff-11ea-987b-7aeef84cdf44.png)

**Comment by williambj1** [comment]
The chat is for github users only, please avoid using gitlab

**Comment by marcelloinfoweb** [comment]
Obrigado!!!
