### ISSUE TITLE
App doesn´t start

### ISSUE THREAD

**Issue by ProfDrLuigi** [OpenIntelWireless/HeliPort#131]
After compiling and starting I get this error. Also in "Programs"-Folder it doesn´t start
![grafik](https://user-images.githubusercontent.com/45099401/88379072-8b149780-cda2-11ea-9f36-d0a618c55519.png)

Other Users get the same error. It´s no "local" problem here.

**Comment by mehmetyukcell** [comment]
> After compiling and starting I get this error. Also in "Programs"-Folder it doesn´t start
> 
> ![grafik](https://user-images.githubusercontent.com/45099401/88379072-8b149780-cda2-11ea-9f36-d0a618c55519.png)
> 
> 
> 
> Other Users get the same error. It´s no "local" problem here.
> 
> 
> 
> 

Heliport app should be delete your all storage drive. No issue

**Comment by williambj1** [comment]
1. You should use the Release version of this software
2. You should delete all the duplicates on your hard drive
3. You should run this app in the Applications folder

If any of those conditions are not met, you will see this error.

**Comment by williambj1** [comment]
https://openintelwireless.github.io/HeliPort/Advanced.html#how-to-build-heliport
