### ISSUE TITLE
[Feature Request]Bionic Airdrop Implementation

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/HeliPort#144]
After we have implemented the basic functions of HeliPort, I have always had an idea about the AirDrop function(Now we don't use Apple's IO80211Family private library, so we should implement these functions ourselves).
- Write our own LAN transmission protocol, we can use HeliPort to transfer files between different devices.
- Compatible with windows LAN transmission protocol.
- Compatible with Apple's original AirDrop transmission.
The first and second points are not technically difficult. As for the third point, there are several points that need to be investigated (note that the following APIs refer to the API of the application layer, eg swift / OC APIs):
  - BLE Bluetooth control API.
  - At present, the driver does not support P2P discovery protocol, so we use LAN discovery technology instead. What existing technologies on Mac OS can quickly discover LAN devices?
  - The file transfer part is a preliminary analysis of TLS, so where to obtain the certificate, and what are the relevant APIs for LAN HTTPS protocol transmission?

**Comment by yanwuu** [comment]
https://github.com/MoKee/android_packages_apps_WarpShare
       
https://github.com/seemoo-lab/opendrop

**Comment by wqhqq1** [comment]
Did you mean you will support "airdrop" in heliport but not in finder?
