### ISSUE TITLE
itlwm is not running

### ISSUE THREAD

**Issue by ZambraDesigner** [OpenIntelWireless/HeliPort#147]
I followed the @daliansky guide but it doesn't work.
![Schermata 2020-08-03 alle 16 06 46](https://user-images.githubusercontent.com/47243056/89219960-0f4ff180-d5d1-11ea-9c91-adb457915169.png)

Error: "itlwm is not running"

Guide: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/Docs/Drive-Native-Intel-Wireless-Card.pdf

**Comment by ErrorErrorError** [comment]
What intel card are you using? You might have to use itlwmx.kext instead of itlwm.kext 


https://openintelwireless.github.io/itlwm/Compat.html#itlwm-kext

Also, please provide logs. You can get logs following here: https://openintelwireless.github.io/General/Troubleshooting.html

**Comment by ZambraDesigner** [comment]
I did an update of Clover and other kext and now I no longer have the error.

Now HeliPort recognizes wifi networks but cannot connect.
And there is no way to delete saved networks to log in again.

**Comment by ErrorErrorError** [comment]
> And there is no way to delete saved networks to log in again.

You can delete saved networks if you click "Open Network Preferences..." in HeliPort and clicking on network tab.

**Comment by SNOOKS4** [comment]
> I did an update of Clover and other kext and now I no longer have the error.
> 
> Now HeliPort recognizes wifi networks but cannot connect.
> And there is no way to delete saved networks to log in again.
> 
> I have a Xiaomi NoteBook Pro 15.6'' with Intel Wireless 8265

Am still getting the error each time I restart please can you help me out

**Comment by williambj1** [comment]
https://github.com/OpenIntelWireless/HeliPort/issues/178#issuecomment-677306392

**Comment by hafizhuzaifabit** [comment]
my mac was working fine with itlwm but i accidenttaly added Airportitlwm too...and now none of them are working and im getting this error..any solution? its urgent pls
