### ISSUE TITLE
Exclamation mark over WiFi icon

### ISSUE THREAD

**Issue by NikolaJ97** [OpenIntelWireless/HeliPort#152]
I have successfully installed latest version of HeliPort and injected itlwm.kext using OpenCore. It located my home wireless network and connects to it, however there is an exclamation mark over the icon and when I enter the network settings, it says it has self assigned IP address. I tried deleting preference plist files so the system can build new ones, however it did nothing. Tried rebooting, tried shutting down and powering on, nothing works. My Intel card is 9560, so as far as I know it is supported. My laptop is Asus Zenbook UX 433 FA.

**Comment by ErrorErrorError** [comment]
> I have successfully installed latest version of HeliPort and injected itlwm.kext using OpenCore. It located my home wireless network and connects to it, however there is an exclamation mark over the icon and when I enter the network settings, it says it has self assigned IP address. I tried deleting preference plist files so the system can build new ones, however it did nothing. Tried rebooting, tried shutting down and powering on, nothing works. My Intel card is 9560, so as far as I know it is supported. My laptop is Asus Zenbook UX 433 FA. 

Check the password. You can remove the saved information from keychain access.

**Comment by williambj1** [comment]
Closed due to inactivity
