### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Heist87** [OpenIntelWireless/HeliPort#157]
**Describe the bug**
When I connect to a wifi repeater, it is a D-link repeater,  HeliPort only connect and disconnect and can't use, but if I connect to the router all ok

**Environment (please complete the following information):**
 - Wifi card Wireless-AC 7265
 - Catalina 10.15.6
 - HeliPort Version 1.0.0 (2abd97a)

**Comment by williambj1** [comment]
1. Check your password
2. Provide logs from HeliPort, use HeliPort's advanced menu to dump it.

Thank.

**Comment by williambj1** [comment]
Closed due to inactivity
