### ISSUE TITLE
New Network Preferences implementation shows only 2.4Ghz networks [Bug]

### ISSUE THREAD

**Issue by idominikosgr** [OpenIntelWireless/HeliPort#163]
**Describe the bug**
The new network preferences instead of showing all networks I have been connected to, it shows only the 2.4Ghz ones.

**To Reproduce**
1. connect to a couple of networks, 5G and 2.4G
2. Store the passwords to keychain
3. Check the preferences for the saved networks

**Screenshots**
All these networks are 2.4Ghz

<img width="732" alt="Screen Shot 2020-08-11 at 11 29 09" src="https://user-images.githubusercontent.com/54411598/89875724-4ff9cd00-dbc6-11ea-9707-1f02b2f3d11e.png">

**Environment (please complete the following information):**
 - OS Version: Big Sur Dev Beta 4
 - Software Version: 1.0 (2abd97a)
- Intel Wifi 8265

**Comment by ErrorErrorError** [comment]
Do the 5g network show up in keychain access? It works fine on my end.

**Comment by idominikosgr** [comment]
The network is stored yes, as a matter of fact I am connected right now but the networks displayed are the ones in the screenshot above.

<img width="646" alt="Screen Shot 2020-08-11 at 11 47 53" src="https://user-images.githubusercontent.com/54411598/89877510-dd3e2100-dbc8-11ea-8f36-a456f331ec49.png">
<img width="332" alt="Screen Shot 2020-08-11 at 11 45 37" src="https://user-images.githubusercontent.com/54411598/89877520-dfa07b00-dbc8-11ea-94fa-af7875d55ff4.png">

**Comment by ErrorErrorError** [comment]
It doesn't show the network because the version stored on the keychain access is version  1 but HeliPort requires version 2. You will not be able to auto join with that network unless if you remove it from keychain access and connecting to the network with the option "Remember network" ticked.

**Comment by idominikosgr** [comment]
Indeed that was the case. Thanks a lot!
