### ISSUE TITLE
[Feature Request] Hide "About HeliPort" menu entry

### ISSUE THREAD

**Issue by mojo2012** [OpenIntelWireless/HeliPort#166]
Seeing the "About HeliPort" menu entry in the standard menu is kinda disturbing.

I think it should be hidden and only shown under the "advanced menu" that is shown on alt-click.

**Comment by Edoardo001** [comment]
> Seeing the "About HeliPort" menu entry in the standard menu is kinda disturbing.
> 
> I think it should be hidden and only shown under the "advanced menu" that is shown on alt-click.

+1

**Comment by Goshin** [comment]
I don't understand why it could be disturbing?

**Comment by ErrorErrorError** [comment]
> I don't understand why it could be disturbing?

I don't mind it either, however from OP's post, they would like it as how macOS Wi-Fi menu shows, but I think it's a bit confusing if you have both menus on, which is recommended to have the native menu icon off.

**Comment by williambj1** [comment]
I was initially thinking about having an option to toggle its appearance, although I don't mind it either.

**Comment by mojo2012** [comment]
I think in a system-like menu the only menu entry not directly related to core-functionality (like update, or about) should not be visible, as it is some sort of distraction. How often do I need to open "about"? Probably once? But it clutters the menu everytime I open it (probably several times a day).

**Comment by Goshin** [comment]
I personally have no interest in making it identical to coreWLAN's appearance. The item is placed at the bottom with a separator, so I think it is unlikely someone can mistake it with other items. About is about, most apps have it as the first menu entry, though most people don't care.

Btw, @williambj1 it is time to update the credits info in About, to include many great developers involved.

**Comment by Voring** [comment]
metoo

**Comment by mojo2012** [comment]
Cool that it has been implemented! Way cleaner that way :-)
