### ISSUE TITLE
Please Add a Icon Toggle for the Newer Wifi Icon (Slik Looking)

### ISSUE THREAD

**Issue by JaiS99** [OpenIntelWireless/HeliPort#174]
⅙The Current Wifi Icon on the menubar is a bit Outdated It would be wonderful if you added a Icon like Mac os 11.0
Please Add a Toggle or Update the Existing Icon to Match That of Big Sur.
Please Note:This is Not a request to update the Heliport Icon but the Icon in the Menu Bar.

**Comment by williambj1** [comment]
Feel free to draw one and contribute.

**Comment by JaiS99** [comment]
Okay Thanks.
