### ISSUE TITLE
Heliport running at an unexpected path

### ISSUE THREAD

**Issue by Seazer-x** [OpenIntelWireless/HeliPort#178]
when i reboot my hackintosh , Heliport'll tell me this
![截屏2020-08-20 14 12 08](https://user-images.githubusercontent.com/62045004/90724553-576d5480-e2f1-11ea-95e9-442c69c2e45e.png)

**Comment by Seazer-x** [comment]
and when i lancher at Debug or not reboot mac it is fine!

**Comment by williambj1** [comment]
You have an invalid version that has `launch at login` enabled.

Run the following command to know where is it located and delete it.

```sh
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep HeliPort.app
```

The reset the database

```sh
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
```

**Comment by Seazer-x** [comment]
![截屏2020-08-21 09 24 02](https://user-images.githubusercontent.com/62045004/90842013-c51c8d80-e390-11ea-828a-447b1f1b0017.png)
And then? i drop HeliPort.app form Debug into **Application** and i reset **launch at login** ,Then i  reboot my hackintosh,but it appear again!

**Comment by Seazer-x** [comment]
This mean i can only relaunch at login from Debug?

**Comment by williambj1** [comment]
You should use the Release version if you’ve decided to use it daily; Debug versions only work in Xcode and you will receive that notification if you moved it elsewhere.

TBH, I would recommended using the one from GitHub release, compiled by CI, for daily use.

**Comment by williambj1** [comment]
Duplicate of #147
