### ISSUE TITLE
[Feature Request] Always show the disconnect item when connected to a network

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/HeliPort#179]
**Is your feature request related to a problem? Please describe.**
The standard macOS Wi-Fi UI always shows the disconnect item when connected to a network. No need to hold Alt when opening the UI.

**Describe the solution you'd like**
Disconnect item to be always shown when connected to a network

**Describe alternatives you've considered**
Holding Alt, but to implement it same way as macOS is more user-friendly and faster to use.

**Comment by ErrorErrorError** [comment]
Hm, my mac shows the "disconnect item" only when pressing Options + WiFi icon. I am on the latest macOS 10.15.6.

**Comment by igorkulman** [comment]
My desktop hackintosh with 10.15.6, but the native Wi-Fi UI using BCM943602CS

![image](https://user-images.githubusercontent.com/4746070/91032508-521a4d80-e602-11ea-8970-9694f7d3878a.png)

**Comment by williambj1** [comment]
@igorkulman 

TBH I've never seen the disconnect menu button on a native card before, did you apply any special changes?

If Apple has it maybe we can add a configuration to toggle this behavior.

**Comment by igorkulman** [comment]
> @igorkulman
> 
> TBH I've never seen the disconnect menu item on a native card before, did you apply any special changes?
> 
> If Apple has it maybe we can add a configuration to toggle this behavior.

No special config, just BCM943602CS installed, not kext or anything else as it is not required.

**Comment by williambj1** [comment]
> > @igorkulman
> > TBH I've never seen the disconnect menu item on a native card before, did you apply any special changes?
> > If Apple has it maybe we can add a configuration to toggle this behavior.
> 
> No special config, just BCM943602CS installed, no kext or anything else as it is not required.

Some people told me the disconnect item only appears when the network has not enabled auto-join, is that your case?

**Comment by igorkulman** [comment]
> > > @igorkulman
> > > TBH I've never seen the disconnect menu item on a native card before, did you apply any special changes?
> > > If Apple has it maybe we can add a configuration to toggle this behavior.
> > 
> > 
> > No special config, just BCM943602CS installed, no kext or anything else as it is not required.
> 
> Some people told me the disconnect item only appears when the network has not enabled auto-join, is that your case?

Actually yes, that must be it, as I Ethernet primarily so I do not have any network set as auto-connect.
