### ISSUE TITLE
[Bug] Not showing security of the connected network

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/HeliPort#181]
**Describe the bug**
In the list of networks when the currently connected network is not open, it does not show the lock next to the signal strength indicator.

**To Reproduce**
1.  Connect to an network that is not open
2. Open HeliPort and take a look at the menu item representing that network

**Expected behavior**
The connected network should show a lock next to the signal strength indicator when not open.

**Screenshots**
![Screenshot 2020-08-24 at 12 10 56](https://user-images.githubusercontent.com/4746070/91033056-1469f480-e603-11ea-90e0-fb18bec1224a.png)

**Environment (please complete the following information):**
 - OS Version: 10.15.6
 - Software Version: 1.0.0

**Comment by zhudav** [comment]
Quickest way to fix this is to include the auth security info in ioctl_sta_info which requires a change to sSTA_INFO in itlwm and itlwmx.  I have it working on my local machine.  If that seems like a reasonable way to go, I can put together a PR for both repos.  Let me know.

**Comment by williambj1** [comment]
> Quickest way to fix this is to include the auth security info in ioctl_sta_info which requires a change to sSTA_INFO in itlwm and itlwmx. I have it working on my local machine. If that seems like a reasonable way to go, I can put together a PR for both repos. Let me know.

@zhudav Yes, that is the desired solution :P

**Comment by zhudav** [comment]
A Pair of PR for the fix created:

https://github.com/OpenIntelWireless/itlwm/pull/278
https://github.com/OpenIntelWireless/HeliPort/pull/186
