### ISSUE TITLE
[Feature Request] Hide network from available networks when already conntected to it.

### ISSUE THREAD

**Issue by NastyGamer** [OpenIntelWireless/HeliPort#182]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Hide the network from the available networks section as long as you're conntected to it. When disconnected, show it again

**Comment by ErrorErrorError** [comment]
That's something that Big Sur does with their Wi-Fi. It wouldn't make sense to hide networks on pre Big Sur because if you would want to connect to other networks while currently connected to a network, you would have to disconnect from the internet first.

**Comment by williambj1** [comment]
We will not create a new UI that imitates Big Sur's. Apple did not use standard menu items to create them.
