### ISSUE TITLE
error when opening HeliPort.dmg

### ISSUE THREAD

**Issue by desmondyipyc** [OpenIntelWireless/HeliPort#188]
after opening HeliPort.dmg, I double clicked Heliport in the IU but it prompt an error "HeliPort running at an unexpected path

Help please

**Comment by mehmetyukcell** [comment]
Please heliport should delete all system drives

**Comment by NastyGamer** [comment]
I think you have to copy the executable into your programs folder prior to opening it.

**Comment by desmondyipyc** [comment]
im new to macos, have never use a mac before can you elaborate more? like with the steps

**Comment by NastyGamer** [comment]
- you double-click the dmg file
- you open finder (The icon which has something like a face on it)
- on the left column you should see a folder called Programs.
- drag the heliport program into the Programs folder.
- open launchpad (the rocket in the dock)
- find heliport and click on in
this tutorial shows the steps (you obviously have to do it with heliport instead) https://www.youtube.com/watch?v=WonYZGt-7Jc

**Comment by williambj1** [comment]
https://openintelwireless.github.io/General/Installation.html#installing-heliport
