### ISSUE TITLE
[Bug] Network not saved if SSID name is long

### ISSUE THREAD

**Issue by masnormen** [OpenIntelWireless/HeliPort#189]
**Describe the bug**
I've discovered that if an SSID name of a network is too long, HeliPort won't store it to Keychain. Therefore it's not saved and needs password everytime I connect.

**To Reproduce**
1. Name an SSID with a long name (e.g "Integrated FBI Intercept Network")
2. Connect and enter password with "remember password" options checked
3. Restart computer
4. Connect to the network again, it asks for password

**Expected behavior**
It should save the password for any network.

When I connect to a much shorter SSID, I can even see that HeliPort immediately stores the password in Keychain Access. But in a network with long SSID it doesn't.

**Screenshots**

Pic 1: Connect to "ibnuhadjar" network, password is immediately saved in keychain.
![image](https://user-images.githubusercontent.com/3425302/92300211-63107a80-ef83-11ea-9c1c-664a4ecad856.png)

Pic 2: Connect to "Integrated FBI Intercept Network" network, password is not saved in keychain (here it only shows the keychain for "ibnuhadjar" network which is previously saved by HeliPort.
![image](https://user-images.githubusercontent.com/3425302/92300340-593b4700-ef84-11ea-8d52-cc8dc18f22cf.png)

**Environment (please complete the following information):**
 - OS Version: Catalina 10.15.6
 - Software Version: 1.0.0 release

**Additional context**
At first, I also suspected if it's an issue with my long password or my wording in SSID. But no. I tried other SSID names with similar length and shorter password and it isn't the case. It only happens in network with long SSID.

**Comment by ErrorErrorError** [comment]
If you don't mind disconnecting from the network and connecting to it again and upload a diagnostics report? Pressing options + WiFi icon and clicking "Create Diagnostics Report..." and upload the zip if you don't mind.

**Comment by masnormen** [comment]
> If you don't mind disconnecting from the network and connecting to it again and upload a diagnostics report? Pressing options + WiFi icon and clicking "Create Diagnostics Report..." and upload the zip if you don't mind.

Here is the diagnostic file. In the log it's around the 14:00 timestamp

[bugreport_1258.zip](https://github.com/OpenIntelWireless/HeliPort/files/5177820/bugreport_1258.zip)

**Comment by ErrorErrorError** [comment]
> > If you don't mind disconnecting from the network and connecting to it again and upload a diagnostics report? Pressing options + WiFi icon and clicking "Create Diagnostics Report..." and upload the zip if you don't mind.
> 
> Here is the diagnostic file. In the log it's around the 14:00 timestamp
> 
> [bugreport_1258.zip](https://github.com/OpenIntelWireless/HeliPort/files/5177820/bugreport_1258.zip)

Are you able to connect successfully to the internet? According to the logs, it looks like it fails to connect which is why it does not save the password.

```
Failed to connect to: Integrated FBI Intercept Network
```

**Comment by masnormen** [comment]
> > > If you don't mind disconnecting from the network and connecting to it again and upload a diagnostics report? Pressing options + WiFi icon and clicking "Create Diagnostics Report..." and upload the zip if you don't mind.
> > 
> > 
> > Here is the diagnostic file. In the log it's around the 14:00 timestamp
> > [bugreport_1258.zip](https://github.com/OpenIntelWireless/HeliPort/files/5177820/bugreport_1258.zip)
> 
> Are you able to connect successfully to the internet? According to the logs, it looks like it fails to connect which is why it does not save the password.
> 
> ```
> Failed to connect to: Integrated FBI Intercept Network
> ```

As you can see in my screenshot 2, it is connected after I inputed password manually. Other times, I don't know why, but it occasionally failed to connect to any network (not just the FBI network) and scans again instead. Maybe because the signal? But the thing is I have been connected to the network many times before I screenshot and it always forgot the password.

But still, the problem here is why it wont save the password to the keychain even after it is connected succesfully many times before. It always asks for a password.

Even after I deleted the keychain manually, after I connect the network "ibnuhadjar" will be remembered by HeliPort immediately. But the network "Integrated FBI Intercept Network" is not.

Well, I don't mind changing my network name to get it remembered. But still, it is a strange problem.

**Comment by ErrorErrorError** [comment]
Does this still happen? Or has it been fixed?

**Comment by masnormen** [comment]
> Does this still happen? Or has it been fixed?
> 
> Edit: looks like it's an issue with non null termination once all the char characters are full. `String(cString:)` works well only if cString has a zero in the char array.

It still is! And thank you for your PR. Hope it gets merged soon

**Comment by ErrorErrorError** [comment]
> It still is! And thank you for your PR. Hope it gets merged soon

If you don't mind cloning my pull request and see if it works fine on your end?

**Comment by masnormen** [comment]
> If you don't mind cloning my pull request and see if it works fine on your end?

Unfortunately I dont have Xcode so I can't build and test. My disk is full enough

**Comment by williambj1** [comment]
@masnormen Could you try this version please? It's built from #211.

[HeliPort-f1484b1.zip](https://github.com/OpenIntelWireless/HeliPort/files/5579422/HeliPort-f1484b1.zip)
