### ISSUE TITLE
HeliPorts wants to use your confidential information stored in "com.OpenIntelWireless.HeliPort" in your keychain.

### ISSUE THREAD

**Issue by Chawucikela** [OpenIntelWireless/HeliPort#192]
An alert dialog shows up when I open the app since I updated it to the version of 1.0.0 stable, it keeps asking me to enter a password that I get no clue of, I've try both my login pw and my AppleId pw, but still not working. The weird thing is the function works well, I suppose it is the update issue.

**Comment by alessiomatricardi** [comment]
I had also this problem some time ago. Probably I installed a new version while it was running. How I solved:
- Remove all Heliport entries from Keychain
- Disconnect from current WiFi and quit Heliport
- reboot your sistem
- Reinstall HeliPort

**Comment by Chawucikela** [comment]
> I had also this problem some time ago. Probably I installed a new version while it was running. How I solved:
> 
> * Remove all Heliport entries from Keychain
> * Disconnect from current WiFi and quit Heliport
> * reboot your sistem
> * Reinstall HeliPort

thx! I'll try it out

**Comment by williambj1** [comment]
Apple's keychain is quite annoying and requires you to enter your password multiple times. It is out of our control.
