### ISSUE TITLE
[Bug] The task bar icon splashes after coming back from lock screen randomly on High Serria 

### ISSUE THREAD

**Issue by richardkindom** [OpenIntelWireless/HeliPort#194]
**Describe the bug**
The task bar icon splashes after coming back from lock screen randomly on High Serria. It appears to search and try to connect to WiFi, while it really doesn't do so.
The background kext works fine even if this issue happens. BTW I am using dual screens.

**To Reproduce**
1. lock Mac and screen goes black
2. unlock Mac and this happens. For sometime, this would not happen.
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 
 - Software Version:

**Additional context**

**Comment by williambj1** [comment]
Please upload a video.
