### ISSUE TITLE
[Bug]i18n error

### ISSUE THREAD

**Issue by Basstorm** [OpenIntelWireless/HeliPort#196]
**Describe the bug**
as title

**Expected behavior**
showing "Disconnect from" in Chinese

**Screenshots**
![image](https://user-images.githubusercontent.com/37471354/94004442-4bccec00-fdcf-11ea-822c-ab8b15ef02f9.png)

**Environment (please complete the following information):**
 - OS Version: 10.15.6
 - Software Version:latest pre-release

**Comment by Basstorm** [comment]
Addition: This is a WI-FI from my mobile phone. My phone was right next to me but the signal was weak

**Comment by ErrorErrorError** [comment]
Hm, I notice that the string still contains a colon. https://github.com/OpenIntelWireless/HeliPort/blob/dac29e9527a2ca31edc1dc841b843b41bc221dbb/HeliPort/Appearance/StatusMenu.swift#L614 

However in the zh.localizable string it contains without the colon. Most of the other ones have no colons for that key anymore so I think it is recommended to remove the colon from that line just to reduce the number of places to make edits.

**Comment by williambj1** [comment]
Fixed in #183
