### ISSUE TITLE
[Feature Request] Open System Networks from the dropdown menu

### ISSUE THREAD

**Issue by ManuGithubSteam** [OpenIntelWireless/HeliPort#200]
**Is your feature request related to a problem? Please describe.**
I can not easily configure the network settings of a connected network. I have to open System Prefs seperatly and open the Network tab,

**Describe the solution you'd like**
Let us open the Network tab from system prefs from the dropdown menu like "Open Network Preferences"
eg. Open System Network Preferences

**Describe alternatives you've considered**
Remap the Open Network Preferences to open the real System Prefs Network Prefs.

**Additional context**
I also would like to hide the about Entry but thats not a big concern. I want mostly to be able to open System Prefs from the dropdown menu.

**Comment by williambj1** [comment]
It's already there, hold the  command key and the menu.

**Comment by ManuGithubSteam** [comment]
Perfect :-) thanks

**Comment by ErrorErrorError** [comment]
> Ok i just tired it and it does not work.
> 
> I have a hackintosh but im Pressing the Windows key, with is normaly  mapped to the command key. If i press the command key and then the left klick on the icon i see the normal menu. No system prefs. Also the menu does not change if i use CTRL or ALT keys. I'm doing it wrong ? Thanks

You press and hold the options key and click on the WiFi menu to show the extra settings.

**Comment by ManuGithubSteam** [comment]
> > Ok i just tired it and it does not work.
> > I have a hackintosh but im Pressing the Windows key, with is normaly  mapped to the command key. If i press the command key and then the left klick on the icon i see the normal menu. No system prefs. Also the menu does not change if i use CTRL or ALT keys. I'm doing it wrong ? Thanks
> 
> You press and hold the options key and click on the WiFi menu to show the extra settings.

If i do that i get a lot of extra diagnostic info like interface name etc and such but no "system preferences" it is just not there.
