### ISSUE TITLE
[Bug]HeliPort 与网易云音乐存在兼容问题？

### ISSUE THREAD

**Issue by godcheese** [OpenIntelWireless/HeliPort#203]
**Describe the bug**
HeliPort 与网易云音乐存在兼容问题？HeliPort 与网易云音乐同时运行，HeliPort 状态栏图标会被隐藏？
**To Reproduce**
1. 运行最新稳定版 HeliPort。
2. 运行最新版网易云音乐。
3. HeliPort 状态图标突然不见，但网络可以连接。
4. 

**Expected behavior**
正常情况下我打开网易云音乐 HeliPort 状态栏图标不应该会被隐藏
**Screenshots**

**Environment (please complete the following information):**
 - OS Version:  macOS 10.15.3
 - Software Version:  
    - HeliPort v1.0.1
    - 网易云音乐 2.3.2 (832)

**Additional context**

**Comment by williambj1** [comment]
Our code generates a native menu with Apple's AppKit API and we did not use any code that behaves specifically with Netease Music. TBH, this issue is out of our control. Maybe consider reporting this issue to Apple or Netease.
