### ISSUE TITLE
[Feature Request] New Icon for Menubar

### ISSUE THREAD

**Issue by R-Teer** [OpenIntelWireless/HeliPort#206]
Is there a possibility to update the menubar icon to be more in line with the newest Mac OS version?

As we are upon release of Big Sur, it would be great to see an implementation that better suits the new UI such as:

[See Here](https://icons8.com/icon/85509/wi-fi)

**Comment by williambj1** [comment]
Duplicate of #174

**Comment by williambj1** [comment]
Duplicate of #182
