### ISSUE TITLE
Not recognising mesh

### ISSUE THREAD

**Issue by MoSchaub** [OpenIntelWireless/HeliPort#208]
**Describe the bug**
I have a mesh of two wifi access points and they are not recognised as the same network the network appears twice

**To Reproduce**
1. Meshed wifi

**Expected behavior**
It should be recognised as one network

**Environment (please complete the following information):**
 - OS Version: 11.0.1
 - Software Version: 1.0.1

**Comment by ErrorErrorError** [comment]
> I have a mesh of two wifi access points and they are not recognised as the same network the network appears twice

What itlwm version are you using?

**Comment by MoSchaub** [comment]
As stated above I am using Heliport Version 1.0.1 (1791555)

**Comment by williambj1** [comment]
> As stated above I am using Heliport Version 1.0.1 ([1791555](https://github.com/OpenIntelWireless/HeliPort/commit/1791555e6cb0e4fed6a2a1ed1f95bdd0b4412019))

Yes, but which version of `itlwm` are you using?

**Comment by MoSchaub** [comment]
I am using the itlwm kext found here https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

**Comment by win1010525** [comment]
Isn't it a issue of itlwm?

**Comment by MoSchaub** [comment]
Probably could be
