### ISSUE TITLE
Improvements for StatusMenu

### ISSUE THREAD

**Issue by williambj1** [OpenIntelWireless/HeliPort#21]
- [x] Show a tick on the left of the connected Wi-Fi
- [x] Set currently connected Wi-Fi as the first Wi-Fi menu item
- [x] Show "Wi-Fi: Looking for Networks..." when itlwm is scanning
- [ ] Add a menu item for disconnecting from currently connected Wi-Fi  
- [ ] Show detailed info of currently connected Wi-Fi
  - [x] IP Address
  - [x] Router
  - [x] Internet
  - [ ] Security
  - [x] BSSID
  - [x] Channel
  - [ ] Country Code
  - [x] RSSI
  - [ ] Noise
  - [x] Tx Rate
  - [x] PHY Mode
  - [x] MCS Index
- NOTE: Personal Hotspot's section will never be added since itlwm can't determine whether a Wi-Fi is an iPhone hotspot, not to mention cellular signal strength and battery info.

**Comment by Edoardo001** [comment]
I suggest also to add a tick to the connections that has stored passwords

**Comment by williambj1** [comment]
@Edoardo001 Hmmm, that doesn’t make sense since Apple didn’t do that and it might be hard to know which WiFi is currently connected.

**Comment by kostaskas** [comment]
Suggest to auto connect on application startup on the latest connected Wifi or one of the saved ones, on my pc I must connect to wireless every time and doesn't save password
