### ISSUE TITLE
[Bug] itlwm is not running

### ISSUE THREAD

**Issue by Thumbkin** [OpenIntelWireless/HeliPort#213]
**Describe the bug**
Cant load Heliport (on login or manualy) since itlwm is not running.

**To Reproduce**
1. Updated opencore to 0.6.4
2. Rebooted
3. Heliport is no longer loading

**Expected behavior**
Normaly Heliport is added as startup application after login, but no longer starts.

**Screenshots**
![Schermafbeelding 2020-12-09 om 14 09 50](https://user-images.githubusercontent.com/42451175/101635351-247ad800-3a2a-11eb-8eff-647a7ae261ed.png)

**Environment (please complete the following information):**
 - OS Version: Big Sur 11.0.1
 - Software Version: 1.0.1 (itlwm v1.1.0, same with 1.2.0)

**Additional context**
- Kext itself is in the right OC directory (see screenshot)
- I checked if kext is loaded (see screenshot)
- itwlm.kext is loaded in config.plist of OC (didnt change that during upgrade OC, see screenshot)
- There is no error in the OC debug.log saying that the kext could not be loaded
- Tried to manualy load kext from terminal and restart Heliport, same message

**Comment by williambj1** [comment]
User configuration issues are not supported here.
