### ISSUE TITLE
continuous disconnections[Bug]

### ISSUE THREAD

**Issue by godzillarzillo** [OpenIntelWireless/HeliPort#214]
**Describe the bug**
every 10 minuts minutes the wifi crashes and can no longer connect

**To Reproduce**
1. while browsing it disconnects
2. i need to disable wifi connection
3. enable again the wifi
4. hope it works or repeat the process

**Environment (please complete the following information):**
 - OS Version: Big Sur
 - Software Version: 11.0.1
[bugreport_31246.zip](https://github.com/OpenIntelWireless/HeliPort/files/5685380/bugreport_31246.zip)
[Log_2020-12-13_21-21-36.log](https://github.com/OpenIntelWireless/HeliPort/files/5685381/Log_2020-12-13_21-21-36.log)

**Comment by williambj1** [comment]
Your router is incompatible with the packages and disconnects your mac when there are too many errors. Try adjusting the MTU size. Closing since this issue is duplicated.
