### ISSUE TITLE
Cannot connect hidden network

### ISSUE THREAD

**Issue by wiljay** [OpenIntelWireless/HeliPort#216]
**Describe the bug**
When i try connect other network (hidden),  Heli port long time show connecting network.

**To Reproduce**
1. select joint other network
2. long time connecting

**Expected behavior**
Try connect same router wifi (no hidden network) can connect.

**Environment (please complete the following information):**
 - OS Version: mac os big Sur 11.1
 - Software Version:1.0.1

**Comment by williambj1** [comment]
Invalid issue format
