### ISSUE TITLE
Two wifi ICONS ?

### ISSUE THREAD

**Issue by influenist** [OpenIntelWireless/HeliPort#218]
How to fix this? On boot I have non working wifi icon and one from heliport. Please advice.

![Screenshot 2021-01-28 at 16 48 00](https://user-images.githubusercontent.com/22964559/106162798-cb593600-6188-11eb-984f-a5aeda022367.png)

**Comment by williambj1** [comment]
Hold <kbd>command</kbd> and drag it off.

Closing since this is unrelated.
