### ISSUE TITLE
User Data Management

### ISSUE THREAD

**Issue by williambj1** [OpenIntelWireless/HeliPort#22]
- [x] Implement a plist manager that stores Wi-Fi data used for remembered SSIDs
- [x] Implement a keychain manager that stores and reads from the system keychain
- [x] Search passwords in keychain based on SSIDs
- [x] Automatically connect known SSIDs when the App & kext launches
- [x] Don't ask for password for a Stored Wi-Fi
- [ ] ~~Ask the user to reenter authentication info when stored data is outdated (e.g. Router reconfiguration)~~

**Comment by williambj1** [comment]
Now we have  a very early draft from #30, we need to improve it further

- Add retry logic when passwords are incorrect
- Use information from the plist
- Implement a user interface that manages all the known SSIDs (Todo in later versions)

**Comment by igorkulman** [comment]
Could you explain the plist thing? Maybe I can help. 

You want to read the plist from itlwm? Or store some other data to some app plist? What data?

**Comment by ErrorErrorError** [comment]
> Could you explain the plist thing? Maybe I can help. 
> 
> 
> 
> You want to read the plist from itlwm? Or store some other data to some app plist? What data?

I think what he wants is plist to save ssids that have the checkmark “Remember this Network” if it successfully connects so that in the future if the app restarts for whatever reason, it looks for saved ssids and compares the networks available and connect.
