### ISSUE TITLE
Application hang after recovering from sleep mode[Bug]

### ISSUE THREAD

**Issue by guoqingbao** [OpenIntelWireless/HeliPort#220]
**Describe the bug**
HeliPort application didn't show connections and frozen after wakeup from sleep mode

**To Reproduce**
1. Sleep the MacOSX (10.14.4)
2. Wakeup after few minutes 
3. HeliPort icon indicating "network connecting" even though the network is actually connected
4. Now click HeliPort icon
5. The application frozen

**Expected behavior**
Automatically reconnect and show connections after wakeup

**Environment (please complete the following information):**
 - OS Version: 10.14.4
 - Software Version: 1.3.1

**Comment by williambj1** [comment]
What happens if you force quit the App and relaunch it after sleep?

**Comment by guoqingbao** [comment]
The App works like normal after forcing to quit and relauch.

**Comment by williambj1** [comment]
Could you try to debug this issue and dig a bit more? I am not able to reproduce this issue on my laptop.

**Comment by guoqingbao** [comment]
Sorry. I don't have XCode installed.
________________________________

**Comment by williambj1** [comment]
Sorry but we can't tell what's wrong on our side without being able to reproduce the issue. Other Mojave users we had contact with did not experience this issue as well. AirportItlwm might be an alternative solution for you.
