### ISSUE TITLE
[Bug] Unable to see password prompt window on Sierra

### ISSUE THREAD

**Issue by Ahmad-B** [OpenIntelWireless/HeliPort#221]
**Describe the bug**
Clicking on a network on the list does not bring up the password prompt window to allow me to enter the password

**To Reproduce**
1. Install HeliPort
2. Select Wi-Fi network with password

**Expected behavior**
Password prompt window to show up allowing me to type the password of the network im trying to connect to

**Environment (please complete the following information):**
MacOS Sierra 10.12.6

**Comment by williambj1** [comment]
Log files? Software version? Will reopen once essential information is properly filled.

**Comment by Ahmad-B** [comment]
I have tried using all the verions available in the releases section (including alpha version).
How can I obtain logs for the app?

**Comment by williambj1** [comment]
Press <kbd>Option</kbd> (<kbd>ALT</kbd>) and click on generate diagnostic report.

BTW, please read our docs.

**Comment by Ahmad-B** [comment]
![Screen Shot 2021-04-03 at 23 33 57](https://user-images.githubusercontent.com/2779936/113493233-76fa6b80-94d5-11eb-9cd1-3cc8e679c666.png)
![Screen Shot 2021-04-03 at 23 35 29](https://user-images.githubusercontent.com/2779936/113493234-77930200-94d5-11eb-8992-958bdff610b0.png)
[Log_2021-04-03_23-30-08.log](https://github.com/OpenIntelWireless/HeliPort/files/6253621/Log_2021-04-03_23-30-08.log)
[Log_2021-04-03_23-31-41-2.log](https://github.com/OpenIntelWireless/HeliPort/files/6253622/Log_2021-04-03_23-31-41-2.log)

Im using the latest version of itlwm (1.2.0). The only way im connecting right now is by setting up my WiFi ssid and password within the itlwm kext directly. Also the "Join other network" panel also does a similar thing -  opens for a microsecond and then closes.

Any advice?

**Comment by williambj1** [comment]
Thanks for your information, I've already installed a VM and started investigating.

**Comment by LBates2000** [comment]
A shame this wasn't addressed. I specifically need a copy of Heliport that works in Sierra 10.12.6 but have been unable to compile it for that target.

The version of Airportitlwm that was floating around throws errors when I try to use it.
