### ISSUE TITLE
[Bug] 10.12.6 需要输入wifi密码的时候没有对话框

### ISSUE THREAD

**Issue by GaryDoooo** [OpenIntelWireless/HeliPort#222]
**Describe the bug**
程序可以运行，可以看到周围的wifi，也可以识别itlwm的网卡。用option键按图标，硬件地址什么都可以看到。如果wifi没有密码，点了就能连上，网络可以正常使用。但是，如果wifi有密码，点了之后什么事情都不会发生。

**To Reproduce**
1. macOS 10.12.6 （我这个是黑苹果）
2. 网卡ac7260
3. 用troubleshooting里面Loading the kext manually方法装的itlwm.kext
4. Heliport 1.4.0 稳定版

**Expected behavior**
应该会有一个对话框跳出来问密码是啥？

**Screenshots**
就是点在有密码的WIFI名字上面之后，下拉菜单消失，然后就没有然后了。

**Environment (please complete the following information):**
 - OS Version: 10.12.6
 - Software Version: 1.4.0 稳定

**Additional context**
如果点Join Other Network。。。会有一个窗口跳出。但是瞬间就消失。眼睛很难看清窗口里面内容。大概是输入id和密码之类。
又试了131和102两个早些的版本也是一样。
其他的窗口跳出都没问题，比如about，preference和updates
有没有手动CLI下面写一个配置文件存密码先凑合用的办法？谢谢

**Comment by williambj1** [comment]
已经在安装虚拟机了，这几天有空看看

**Comment by GaryDoooo** [comment]
Thank you very much
