### ISSUE TITLE
[Feature Request] Wpa2 enterpise

### ISSUE THREAD

**Issue by vaqif14** [OpenIntelWireless/HeliPort#223]
Describe the bug
When i try to connect WPA2 Enterprise, Heli port show  Network Security is not supporting WPA2 ENTERPRISE.

To Reproduce

Environment (please complete the following information):

OS Version: mac os Big Sur 11.1
Software Version:1.4.0

**Comment by williambj1** [comment]
Use AirportItlwm as an alternative solution, this features needs to be implemented in itlwm first.
