### ISSUE TITLE
[Feature Request] Any way to control Wifi ON or OFF from command line in Heliport?

### ISSUE THREAD

**Issue by kocoman1** [OpenIntelWireless/HeliPort#224]
[Feature Request] Any way to control Wifi ON or OFF from command line in Heliport?

I find that when my connection does not work, ie: connected but ping times out. I am able to fix it with Heliport's Turn Wifi Off, then Turn Wifi On.  Is it possible to control that from command line so I can add some watchdog that does it automatically for me? thx

**Comment by zxystd** [comment]
ifconfig enx down
ifconfig enx up

x means your interface number, you can get it by ifconfig

**Comment by kocoman1** [comment]
ok it works do you know of any app/script that monitors internet/watchdog to run those commands?  i think this "hang" problem wont be solve soon. 

i tried the mtu but it still does not work 

thx

**Comment by williambj1** [comment]
@kocoman1 

> Any way to control Wifi ON or OFF from command line in Heliport?

HeliPort provides an NSService that could do so. Calling it from commands should be possible.

> do you know of any app/script that monitors internet/watchdog to run those commands?

```sh
function urlTest() {
    while : ; do
        if [[ "$( curl -s captive.apple.com | grep -i "success")" ]]; then
            sleep 10
        else
            echo "Disconnected at $(date)"
            reconnect # Implement this method
        fi
    done
}
```

> i think this "hang" problem wont be solve soon.

Instead of using certain methods as workarounds, I think it would be better to provide logs and actually fix the problem; please create a separate issue for itlwm.
