### ISSUE TITLE
wifi密码输入错误之后无法再次更改密码？[Bug]

### ISSUE THREAD

**Issue by sky508** [OpenIntelWireless/HeliPort#225]
**Describe the bug**
1、在连接Wi-Fi时，采用记住密码的形式，但是如果密码输入错误，由于记住了密码，就无法再次连接这个wifi了，请问怎么解决？
2、Heliport安装之后无法卸载干净：我之前在电脑装了一个1.0.0，但是由于设置了这个自启动，卸载之后再次开机还是会出现这个1.0.0的这个版本的Heliport，请问这是怎么回事？或者能告诉我如何才能清除干净吗？
**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 
 - Software Version:

**Additional context**

**Comment by williambj1** [comment]
可以去 heliport 的偏好设置里删除，或者用连接到其他网络重新连接。目前 itlwm 的 api 不会给回连接失败的原因。

**Comment by jack338c** [comment]
heliport 版本1.5.0
和楼主的情况一样,测试3台不同型号的电脑：拖拉、删除都不起作用，
下面是录屏视频
[https://fu.ssgaff.cn:9876/api/public/dl/9-FvdVVb?inline=true](https://fu.ssgaff.cn:9876/api/public/dl/9-FvdVVb?inline=true)
