### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by daxiewang** [OpenIntelWireless/HeliPort#228]
**Describe the bug**
之前一直用的都没有问题，今天突然发现搜索不到任何wifi列表了，无论怎么点开启wifi都没有用。
**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16398488/122636569-8aa09000-d11c-11eb-9148-fef109970450.png)

**Environment (please complete the following information):**
 - OS Version: 10.14.6
 - Software Version:1.4.0

**Additional context**

**Comment by williambj1** [comment]
No logs, no evidence.
