### ISSUE TITLE
[突然搜索不到列表了,无法开启wifi]

### ISSUE THREAD

**Issue by daxiewang** [OpenIntelWireless/HeliPort#229]
Describe the bug
之前一直用的都没有问题，今天突然发现搜索不到任何wifi列表了，无论怎么点开启wifi都没有用。
To Reproduce
1.开机
2.查看heliport界面，没有wifi列表，开启wifi按钮点了也没有效果
查看日志：
输入命令：kextstat | grep -i "itlwm"
结果：
   70    0 0xffffff7f83482000 0xcde000   0xcde000   com.zxystd.itlwm (1.3.0) 1EB4A67B-0FED-3F45-A1DD-B7DA5FBC5208 <16 13 6 5 3 1>
截图：
![image](https://user-images.githubusercontent.com/16398488/122638810-e113cb80-d128-11eb-8f5d-cf5972de4e0f.png)

Screenshots
image
![image](https://user-images.githubusercontent.com/16398488/122638768-9f832080-d128-11eb-8720-215c1d520d1e.png)

Environment (please complete the following information):

OS Version: 10.14.6
Software Version:1.4.0

**Comment by williambj1** [comment]
Duplicate of #228
