### ISSUE TITLE
Wifi can't enable after turn off wifi , need restart to turn on wifi

### ISSUE THREAD

**Issue by yaza-putu** [OpenIntelWireless/HeliPort#230]
**Describe the bug**
wi-fi can't turn on after turn-off wifi, need restart to turn on wifi

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 10.15.7
 - Software Version: v1.4.0
![Screen Shot 2021-06-19 at 21 20 47](https://user-images.githubusercontent.com/59905886/122643819-86886880-d144-11eb-9aae-571803f372b7.png)

**Comment by gujiwuqing** [comment]
I have also encountered this problem, and it is useless to reinstall it. How to solve it

**Comment by williambj1** [comment]
No logs.

**Comment by gujiwuqing** [comment]
you are very good ！ Not solve the problem？
