### ISSUE TITLE
[Bug] 关闭WiFi后无法重新打开

### ISSUE THREAD

**Issue by gujiwuqing** [OpenIntelWireless/HeliPort#231]
**Describe the bug**

**To Reproduce**
1. 前两天关闭WiFi以后 再次打开点击无效
2. 重新安装版本 也是一样 无法打开 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 
 - Software Version:

**Additional context**

**Comment by williambj1** [comment]
No logs.
