### ISSUE TITLE
[Feature Request] Custom BSSID

### ISSUE THREAD

**Issue by XEmpty** [OpenIntelWireless/HeliPort#235]
Hello, I have noticed in recent hours changes regarding the new API with SSID. Will it be possible to determine the BSSID with the new api? If it is possible to add such functionality along with the new API, it would be great.

Eg: BSSID list available with currently connected network. Or you can enter it manually.

**Comment by williambj1** [comment]
It's already available when you open HeliPort's advanced menu. (Same method as Apple's)

I did not quite understand the "enter it (BSSID) manually" part, could you please elaborate on that?

**Comment by XEmpty** [comment]
I will give an example from linux. From the CLI NetworkManager you can get a list of available BSSIDs for different networks. And then connect to a specific one when you think you need one. It's mainly about choosing a BSSID that works at 5GHz or just different network channel.

Often times, the network fails to connect to 5Ghz by default due to range. In Windows and Linux, it is possible to connect to the BSSID of the current network despite the poor coverage. This can be done in two ways. Either set the "FORCE" mode which automatically selects 5Ghz BSSID, or do it manually by entering the given BSSID.

Sometimes the BSSID change is due to the desire to change the network channel. All cases have a common denominator, no modem access.

**Comment by williambj1** [comment]
Sorry for the late reply.

Specifying a BSSID will require a complete rewrite in itlwm's scanning framework and I sorry to say that we are not planning to do so in the near future. Pull requests are well come and appreciated.
