### ISSUE TITLE
Minor UI bug on available WIFIs listing 

### ISSUE THREAD

**Issue by iamacm** [OpenIntelWireless/HeliPort#240]
### What happened?

The background of the available wifi list is inconsistent. The background is fine after I hover them. 

### Steps To Reproduce

OS: MacOS High Sierra Version 10.13.6 (17G14042)
Dark mode menu bar and dock

### Software Version

10.13.6 (17G14042)

### OS Version

10.13.6 (17G14042)

### Relevant Log Output

![Screen Shot 2022-03-17 at 7 41 25 PM](https://user-images.githubusercontent.com/5087243/158801883-d5ab0bd0-b770-4925-9a28-6e2c00632dbb.png)

**Comment by williambj1** [comment]
This is not the case anymore in v1.5.0, if not feel free to comment below. Thanks.
