### ISSUE TITLE
[Bug]: itlwm未运行

### ISSUE THREAD

**Issue by imzixel** [OpenIntelWireless/HeliPort#249]
### What happened?

打开Heliport后显示itlwm未运行
![image](https://github.com/OpenIntelWireless/HeliPort/assets/108412338/f0b21a28-7c11-4647-96be-cce7d74d8533)

### Steps To Reproduce

已将itlwm.kext复制到kexts文件夹，且终端中输入kextstat | grep -i “itlwm”显示itlwm.kext已经成功加载
![FFCC5EF5-FAC3-479C-84A7-B56FBBE6F0D9](https://github.com/OpenIntelWireless/HeliPort/assets/108412338/2ea1aa8d-4009-4111-bdf2-a467f9fea5dc)
无线网卡：英特尔 Wireless-AC 8265

### Software Version

1.4.1

### OS Version

12.7.2

### Relevant Log Output

[bugreport_41644.zip](https://github.com/OpenIntelWireless/HeliPort/files/13822325/bugreport_41644.zip)

**Comment by zxystd** [comment]
8265可以工作的，自行检查原因。
