### ISSUE TITLE
Updater improvements

### ISSUE THREAD

**Issue by williambj1** [OpenIntelWireless/HeliPort#31]
Currently, the updater framework works fine but we should make it even better.

- [x] Force users to install the app into the `Applications` folder

  > According to Sparke's docs:
  >
  > If you distribute your app as a ZIP or a tar archive:
  > - Encourage users to move the app to /Applications (e.g. use LetsMove). Due to 
  > - quarantine/translocation the system will not allow the app to update itself until it’s moved.

  I personally think LetsMove is not a great idea since it shows a "suspicious" window and an optional moving button. Instead, it's better to pack the app into a dmg and encourage users to move it into the `Applications` folder. We could then force quit the app when the app's location is incorrect.

  So far, I've found those useful tools for creating dmgs

  1. https://github.com/sindresorhus/create-dmg
  1. ~~https://github.com/create-dmg/create-dmg~~

  ~~I've already tested the first one and it works beautifully, however, it lacks the ability of customization and I'd like to use a more intuitive image for the background of the dmg. It also requires a ton of dependencies to generate the dmg icon which I think might be better to just generate it locally and commit it into this repo (maybe under the .github folder). My plan is to use some resources generated from the first tool and pack them into a dmg generated by the second tool.~~
   **Update: Ended up using the first tool since it's much simpler**

- [ ] ~~Support dark mode in Sparkle's release notes~~
   - After using Github's CSS, the window always shows a white background

- [x] Check itlwm API version and force the users to update the app or force quit the app when there's a version mismatch
https://github.com/zxystd/HeliPort/blob/5cdf86d9447d96b2efb62023e57b3b16f6a44250/Common/Common.h#L24

**Comment by mehmetyukcell** [comment]
![Ekran Resmi 2020-06-23 13 00 43](https://user-images.githubusercontent.com/62822060/85392956-ea3d7d00-b554-11ea-9dd1-0db1f0cbe394.png)
![Ekran Resmi 2020-06-23 13 01 06](https://user-images.githubusercontent.com/62822060/85392960-eb6eaa00-b554-11ea-87cb-71991269ad6d.png)
Not updated...
