### ISSUE TITLE
[Feature Request] Launch at login

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/HeliPort#42]
**Is your feature request related to a problem? Please describe.**
After login the user has to start the app manually. The ability for the app to be automatically launched at login would be more comfortable. 

**Describe the solution you'd like**
A menu item saying `Launch at login` than can be enabled or disabled.

**Describe alternatives you've considered**
Adding the app to login items manually, but that is not exactly user friendly.

**Additional context**
Basic implementation tutorial: https://theswiftdev.com/how-to-launch-a-macos-app-at-login/

**Comment by naveenkrdy** [comment]
bump ! 
that would be great and i think `Launch at login` option should only appear when pressing wifi icon with alt key to keep the main wifi menu clean.
