### ISSUE TITLE
[Feature Request] Connect to Open WIFI (no password needed) networks

### ISSUE THREAD

**Issue by gplast** [OpenIntelWireless/HeliPort#60]
Hello and thank you for this incredible work!

I have a guest wifi network on my university and since WPA/WPA2 Enterprise is not implemented, i would like to be able to connect to the open wifi. I can click on the network but is not letting me press OK if i don't fill in a password.

This is just a suggestion, since i included my network on the info.plist and i can connect, but it will be nice to make it work on open wifi also through the Heliport :)

Thank you again!

**Comment by igorkulman** [comment]
As a temporary workaround you can do "Join other network" and fill in the name manually.

**Comment by cly1998** [comment]
I also have this problem. How can I solve it

**Comment by igorkulman** [comment]
@gplast I think this should work with the latest itlwm and latest HeliPort, as the network security is now detected.

**Comment by gplast** [comment]
Thank you @igorkulman for the fast reply,

I built the latest version and used them but currently i do not have access to my UNI wifi. I created a hotspot on my phone though and indeed it didn't ask for a password and was trying to connect. Unfortunately, after a few minutes is still trying to connect but is not connecting. I will test it on the actual Wifi on Monday and let you know.

**Comment by williambj1** [comment]
@gplast Could you test it with the latest commit in itlwm? https://github.com/OpenIntelWireless/itlwm/commit/28feaebd5c9ea500e12e8f99b7aed4090843d374

**Comment by gplast** [comment]
@williambj1 sorry for my late reply, i tested it on a hotspot from my mobile and is connecting now! Thank you for that. I will test it also tomorrow at work just to verify it and let you know! 

Thank you again for all the work!

**Comment by gplast** [comment]
@williambj1 Tested it on my University guest wifi and is working perfectly!

Thank again

**Comment by williambj1** [comment]
Glad that it's fixed, have a nice day.

**Comment by gplast** [comment]
You too :)
