### ISSUE TITLE
[Bug] UI issues on macOS Big Sur

### ISSUE THREAD

**Issue by williambj1** [OpenIntelWireless/HeliPort#66]
**Those issues are likely related to Apple's bugs in AppKit, this GitHub Issue is created to avoid duplicate reports, we have no plans to fix them unless they are still present in Apple's GM release.**

**Describe the bug**
- WifiMenuItem is no longer highlightable after #61 was merged
- JoinPopWindow is not resizeable when different encryptions are selected and everything overlays each other

**Screenshots**

![image](https://user-images.githubusercontent.com/45396585/87162084-092f6380-c2f8-11ea-84b5-17e4f899772e.png)

**Environment (please complete the following information):**
 - OS Version: macOS Big Sur 20A4299v
 - Software Version: 87b614c

**Additional context**
Reproducible in both macOS 10.16 and 10.15's SDK.

**Comment by ErrorErrorError** [comment]
Does the text and icon color switch when you hover over items?

**Comment by williambj1** [comment]
> Does the text and icon color switch when you hover over items?

They become a bit grey, but it’s really hard to notice.

**Comment by ErrorErrorError** [comment]
> > Does the text and icon color switch when you hover over items?
> 
> 
> 
> They become a bit grey, but it’s really hard to notice in dark mode.
> 
> In light mode, the text and icons change their color to white but there are no blue surroundings. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/45396585/87169914-39c8ca80-c303-11ea-905c-0b48b39d135f.png)
> 
> > When is mouse above the first item

Hm then it’s most likely an issue with the NSMenuItemViewer not descending from NSVisualEffectsView. Is it possible If you can check if NSMenuItemViewer descends from NSVisualEffectsView using the view hierarchy debugger?

**Comment by williambj1** [comment]
I haven't used the hierarchy debugger before but I'll certainly give it a try when I'm free in the next few days.

**Comment by williambj1** [comment]
Hmmm, I just gave it a quick try but unfortunately, HeliPort always hangs without responding after I turn on the debugger and try to open StatusMenu.

**Comment by ErrorErrorError** [comment]
> Hmmm, I just gave it a quick try, but unfortunately HeliPort always hangs without responding after I turn on the debugger and try to open StatusMenu.

That’s fine I’ll check it out when Big Sur is officially released and fixed those other issues with API’s

**Comment by ErrorErrorError** [comment]
> * JoinPopWindow is not resizeable when different encryptions are selected and everything overlays each other

I might have fixed this issue with one of branch by converting everything into autolayout. The only issue right now is that I need to hide the paddings when the view is hidden. Can you test and see if the window resizes now by using https://github.com/ErrorErrorError/HeliPort/commits/window-responder and let me know if it fixes the resizing issue?

**Comment by valinor61** [comment]
ths issue fixed with last commit tested in bigsur public beta

**Comment by ErrorErrorError** [comment]
> ths issue fixed with last commit tested in bigsur public beta

Yeah it should fix the issue with resizing. I can fix the issue with highlight later.

**Comment by williambj1** [comment]
Fixed in #156 #183.
