### ISSUE TITLE
[Feature Request] Allow only single instance.

### ISSUE THREAD

**Issue by gimdh** [OpenIntelWireless/HeliPort#67]
**Is your feature request related to a problem? Please describe.**
You may open multiple HeliPorts, yet there is no straightforward way to close it.

**Describe the solution you'd like**
Allow only single instance to be run. Executing new instance should replace existing one.

**Describe alternatives you've considered**
Add quit HeliPort button. You may open multiple HeliPorts, but at least it can be closed with GUI.

**Additional context**
As long as HeliPort is distributed as an indepedent executable, there is always a chance to open multiple instances.

**Comment by Goshin** [comment]
Hold the `opt` key and click the icon, then you can see a "quit" item at the bottom.

**Comment by williambj1** [comment]
Limiting the user to launch a single instance makes sense, we'll implement this in the future.

**Comment by igorkulman** [comment]
@gimdh do you have a way to reproduce this? Because macOS limits this by default, disallowing multiple instances of the same app running.

If I run HeliPort.app it shows in the menu bar, if I run it again, nothing happens, I do not get another instance running.

**Comment by williambj1** [comment]
Hmmm, I've realized that as well. Running multiple instances could usually be achieved by using Xcode or command line.

**Comment by igorkulman** [comment]
> Hmmm, I've realized that as well. Running multiple instances could usually be achieved by using Xcode or command line.

Yes, you would have to be using Xcode or a different executable file. So not exactly a common use case.

**Comment by gimdh** [comment]
My bad. I mistakenly opened two different builds of HeliPort, and overlooked UNIX's single instance policy. I confirm it is not an issue in normal use case, thus closing issue.
