### ISSUE TITLE
[Feature Request] Add a "Quit" menu entry at the bottom or allow Cmd+Q when HeliPort is open

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/HeliPort#76]
**Is your feature request related to a problem? Please describe.**
Yes: I cannot quit the application without force-killing it.

**Describe the solution you'd like**
In the drop-down menu of HeliPort right at the very bottom, kindly add a "Quit HeliPort" under a menu separator, so we can quit the application (and updated it with some later version). At the very least, allow the keyboard shortcut Cmd+Q to quit the application when the drop-down menu is visible.

**Describe alternatives you've considered**
 Currently there is no official way to quit HeliPort. Even when I select "About" and the window is visible, the Cmd+Q shortcut is not working (system beeps instead).

**Additional context**
Some applications may not have a "Quit" menu entry but allow Cmd+Q to quit the application completely. Adding a Quit menu entry (with the respective Cmd+Q icon like macOS standards) would be very welcome.

Thank you.

**Comment by ErrorErrorError** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Yes: I cannot quit the application without force-killing it.
> 
> 
> 
> **Describe the solution you'd like**
> 
> In the drop-down menu of HeliPort right at the very bottom, kindly add a "Quit HeliPort" under a menu separator, so we can quit the application (and updated it with some later version). At the very least, allow the keyboard shortcut Cmd+Q to quit the application when the drop-down menu is visible.
> 
> 
> 
> **Describe alternatives you've considered**
> 
>  Currently there is no official way to quit HeliPort. Even when I select "About" and the window is visible, the Cmd+Q shortcut is not working (system beeps instead).
> 
> 
> 
> **Additional context**
> 
> Some applications may not have a "Quit" menu entry but allow Cmd+Q to quit the application completely. Adding a Quit menu entry (with the respective Cmd+Q icon like macOS standards) would be very welcome.
> 
> 
> 
> Thank you.

If you want to quit the app you have to press and hold options key while clicking on the WiFi icon. You should see an option that says "Exit HeliPort".

**Comment by mackonsti** [comment]
Thanks a nice hidden shortcut. Thank you @ErrorErrorError

**Comment by mackonsti** [comment]
Please @williambj1 kindly document this shortcut in your main page, I checked again, it is nowhere to be found. Thanks!

**Comment by williambj1** [comment]
Sure, I will include this our WIP docs, thanks for your suggestion!
