### ISSUE TITLE
[Bug] Minor UI issues: Text color in About Heliport is abnormal in macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/HeliPort#78]
**Describe the bug**
a) In About window, the text is not visible in Dark Theme.
b) When checking for updates, we get an error (wrong URL?)

**Steps to reproduce the behaviour:**

1. Set dark system theme (I am in Mojave)
2. Select About from menu
3. The About window displays but text is black (see image)
and
1. Keep pressing Option key to show special menu
2. Select to Check for Updates
3. An error is produced

**Expected behavior**
a) I would expect to see the text in About window under dark system theme;
b) I would expect some kind of update information (if the system is in place)

**Screenshots**
![Screenshot 2020-07-15 at 00 46 01](https://user-images.githubusercontent.com/1313613/87488611-21c5b380-c641-11ea-8d69-22f7ef560f1a.png)

![Screenshot 2020-07-15 at 00 46 49](https://user-images.githubusercontent.com/1313613/87488617-24c0a400-c641-11ea-8032-69e68bccc76c.png)

**Environment (please complete the following information):**
 - OS Version: Mojave 10.14.6
 - Software Version: HeliPort Build 13 July 2020 (via automatic builds, see below)

**Additional context**
* Not sure if the text can change based on system theme?
* Not sure if the update URLs are ready? According to Little Snitch it's calling *heliport.bat-bat.workers.dev*
* Please know that I am getting my compiled HeliPort builds from https://github.com/1hbb/OpenIntelWireless-Factory/releases as I **cannot** build the application (not Xcode specialist nor on Catalina) so perhaps the script builds it with wrong parameters -- I am only speculating. Thank you!

**Comment by williambj1** [comment]
Update is working fine, it shows an error because it fetches from GitHub releases and we haven’t posted a release yet.

About HeliPort:
CC @Goshin

**Comment by mackonsti** [comment]
Thanks @williambj1 for your update.
Also to note to @Goshin that I can't close About window with Cmd+W (sorry... many years power user and quick with keyboard shortcuts). Thanks guys. Merci

**Comment by williambj1** [comment]
@mackonsti Does command + w work with other app's about window, for example IOregistryExplorer, MaciASL etc?

**Comment by Goshin** [comment]
> Describe the bug
> a) In About window, the text is not visible in Dark Theme.

cannot replicate it on Catalina, help wanted.

> Also to note to @Goshin that I can't close About window with Cmd+W

It requires a main menu to implement this, but HeliPort as a menu bar app doesn't have one. Won't fix. Pull requests are always welcome.

**Comment by mackonsti** [comment]
> cannot replicate it on Catalina, help wanted.

Hi and thanks, you obviously refer to dev help, not mine... But it's not major so as to give you a headache.
 
> It requires a main menu to implement this, but HeliPort as a menu bar app doesn't have one. Won't fix. Pull requests are always welcome.

Understood, makes sense. I was thinking more of a property of the window itself. No worries. I can still close it by clicking on the red dot :-D

**Comment by ErrorErrorError** [comment]
In Mojave API Apple states:

> Appearance-Aware Credits
You make the credits area match the appearance of an app by supplying the credits as an attributed string or by placing a Credits.rtf or Credits.rtfd in your app’s bundle. Use the proper system colors, like textColor, linkColor, and labelColor, to make text display correctly in any appearance.

So changing the text color to `textColor` attribute should fix the issue.

**Comment by Goshin** [comment]
@ErrorErrorError thanks, fixed in https://github.com/OpenIntelWireless/HeliPort/commit/05026821cb164145c8c02dd71318067c23491ee2

@mackonsti can you test it and see if it works on Mojave?

**Comment by mackonsti** [comment]
Sure @Goshin please give me a couple of days. As I can't build neither the driver nor the app, I will need to wait for the automatic daily builds to include this commit. Thanks again to @ErrorErrorError and everyone for your efforts

**Comment by mackonsti** [comment]
Hi guys, thank you for your quick fix. Works on Mojave :-)

![About Fixed](https://user-images.githubusercontent.com/1313613/87831467-dfd87f80-c883-11ea-987d-6f7c2ed0167b.png)

Please consider this ticket fixed. Have a good weekend!
