### ISSUE TITLE
[Bug] Problem with WIFI auto connect and keychain access.

### ISSUE THREAD

**Issue by naveenkrdy** [OpenIntelWireless/HeliPort#88]
Heliport doesn't automatically connect to last remembered/connected network and needs to be done manually on every boot.
And also i think there is a bug with the keychain implementation as it sometimes ask keychain access password even before it asks wifi network password. And whenever it does ask keychain access password before wifi access password ,i cant type anything in the keychain access password box and thus i have to click deny to make it disappear and only after that the wifi network password box pops up.

AX200
10.15.6

Regards !

**Comment by williambj1** [comment]
CC @Goshin @igorkulman

**Comment by ErrorErrorError** [comment]
> it sometimes ask keychain access password even before it asks wifi network password

That's how it is supposed to work, well according to Catalina permissions regarding to accessing Keychain info.


> And whenever it does ask keychain access password before wifi access password ,i cant type anything in the keychain access

Yeah this is something I have experienced for a while now.

**Comment by igorkulman** [comment]
> it sometimes ask keychain access password even before it asks wifi network password

Not a bug, the app first checks the keychain if a password for the network you are trying to connect to is already saved so it will not ask you if not needed

> And whenever it does ask keychain access password before wifi access password ,i cant type anything in the keychain access password box and thus i have to click deny to make it disappear and only after that the wifi network password box pops up.

This is a bug.

**Comment by naveenkrdy** [comment]
> And whenever it does ask keychain access password before wifi access password ,i cant type anything in the keychain access password box and thus i have to click deny to make it disappear and only after that the wifi network password box pops up.
> 
> This is a bug.

good to know. thanks !

**Comment by Goshin** [comment]
@naveenkrdy it should be fixed in #90. Can you test it?

**Comment by naveenkrdy** [comment]
> @naveenkrdy it should be fixed in #90. Can you test it?

the second issue is now fixed but the first issue i.e auto connect still doesnt work.
thanks for the fix .

**Comment by Goshin** [comment]
@naveenkrdy try cleaning up all the saved passwords of HeliPort in Keychain Access, and save your network again.

**Comment by naveenkrdy** [comment]
> @naveenkrdy try cleaning up all the saved passwords of HeliPort in Keychain Access, and save your network again.

Tried that too and also rebuilt heliport with latest commit and tried again after clearing heliport from keychain but still no dice.
doesnt auto connect to last connected network on launch.

**Comment by 1Revenger1** [comment]
I noticed that connectSavedNetworks isn't called when I last put print statements in there. I did see a reference to it in init for one of the classes, but that was the only place I saw it.

**Comment by Goshin** [comment]
Would it be possible that Itlwm has already connected to a network?

https://github.com/OpenIntelWireless/HeliPort/blob/0103648b56a2eae2b83e0be00f77d1246e02ca09/HeliPort/Appearance/StatusMenu.swift#L384-L389

**Comment by 1Revenger1** [comment]
Yep, doesn't run.
I restarted macOS, loaded itlwm, waiting a minute, then opened HeliPort.
It didn't autoconnect or attempt to do so.

GetDeviceInfo is ran, but get_station_info appears to return KERN_SUCCESS

**Comment by ErrorErrorError** [comment]
Lol the if statement is just checking if the station was able to access heliport, which is why it returns success. It should check if staInfo == ITL80211_sRUN (or the state that checks if it has a connection or not)

**Comment by Goshin** [comment]
OK, have made a fix in master and hope it works. @zxystd told me `get_station_info` will return an error if not connected, but anyway it would be better to double-check the state.

**Comment by 1Revenger1** [comment]
Yep, that works. Any reason why it's only called in init for now? It'd make sense to try and connect to other networks possibly if they are in the scan list and the user moves to another network.

**Comment by ErrorErrorError** [comment]
> OK, have made a fix in master and hope it works. @zxystd told me `get_station_info` will return an error if not connected, but anyway it would be better to double-check the state.

Oh in that case then well we should test a bit more. I just got a bit used to relying get_80211_state, but lets see if other people are able to autojoin.

**Comment by naveenkrdy** [comment]
now it auto connects on login : )

closing issue as resolved !
thanks !
