### ISSUE TITLE
Inverted translation On/Off in pt-BR

### ISSUE THREAD

**Issue by marcelloinfoweb** [OpenIntelWireless/HeliPort#91]
The on/off translation is inverted into Brazilian Portuguese.

How could I help for the maintenance of the translation in pt-BR?

**Comment by williambj1** [comment]
1. Fork this Repo
2. Navigate to your own fork on GitHub
3. Use the built-in editor to change it.
4. Create a pull request.

You can get more details about how to contribute from GitHub's help page or Stackoverflow.

Thank you very much for the report.

**Comment by Aldo97** [comment]
@marcelloinfoweb if you're not able to make a pull request I would more than happy to help you.
In case the Brazilian file has some missing translation, could you please translate what's missing?
Thanks.

**Comment by marcelloinfoweb** [comment]
@Aldo97 Of course I can, I would be very happy to help a project that helped me.
