### ISSUE TITLE
[Bug] Showing as connected to previous network when connecting to another network

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/HeliPort#92]
**Describe the bug**
If you are connected to network A and choose to connect to network B, the app displays being connected to A for a while, then later (next "scan"?) finally shows as connected to B.

**To Reproduce**
1. Open the app
2. Connect to network A
3. Connect to network B
4. Observe the list of network, you will see being connected still to A for a while before it shows as connected to B, although you are already connected to B

**Expected behavior**
The app should show connected to B immediately after successful association. 

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 10.15.6
 - Software Version: 0502682

**Comment by williambj1** [comment]
Confirmed.

**Comment by Goshin** [comment]
Updating for the connected network should be independent from network scanning. It needs refactoring work in both API and UI. I will make a fix soon.
