### ISSUE TITLE
[Bug]Wi-Fi Network seen randomly with and without security

### ISSUE THREAD

**Issue by Aldo97** [OpenIntelWireless/HeliPort#99]
**Describe the bug**
One or more network that requires a password is shown randomly as open(I think it happens 1/2 of the times) when connected on another network.
Turning off and on the Wi-Fi solves this problem. 

**To Reproduce**
1. Open HeliPort 
2. Let the wifi connect to the saved network automatically
3. Check the wifi networks available

**Expected behavior**
It needs to be consistent showing the real security protocol of the networks

**Screenshots**
![IMG_20200717_234341~3.jpg](https://user-images.githubusercontent.com/67073034/87833879-385e4b80-c889-11ea-9545-17ca0efb30ed.jpg)
![IMG_20200717_234502~3.jpg](https://user-images.githubusercontent.com/67073034/87833885-3bf1d280-c889-11ea-9777-f86762f64e9a.jpg)

Sorry for the poor quality of the second photo.

**Environment (please complete the following information):**
 - OS Version: Catalina (10.15.6)
 - Software Version: both HeliPort  (3a9c92b) and itlwm synced with the last commit of the master branch

**Comment by Aldo97** [comment]
It seems that with the last commits this bug is solved

**Comment by Aldo97** [comment]
I had to reopen this issue. I still have this problem with last commits.

**Comment by williambj1** [comment]
I'm not able to reproduce this issue, it may be fixed in a later API change.
